/*
 Navicat MySQL Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80026
 Source Host           : localhost:3306
 Source Schema         : nacos_config

 Target Server Type    : MySQL
 Target Server Version : 80026
 File Encoding         : 65001

 Date: 29/03/2022 18:36:46
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 79 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (4, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n    username: user_hxl\n    password: hxl201803\n  redis:\n    host: 192.168.111.10\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n    connection-timeout: 50000\n  port: 8089\n    \n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', '84a3dbf123fd7fe3ee72d7818072eebe', '2022-01-19 10:58:16', '2022-03-28 12:02:04', 'nacos', '0:0:0:0:0:0:0:1', '', '791df34c-7c81-453e-b01d-375e4a30b834', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (13, 'face-recognition', 'FACERECOGNITION_GROUP', '[\n    {\n        \"resource\": \"select\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"register\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"delete\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"testing\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 2,\n        \"clusterMode\": false\n    }\n]', '09a9defb30ddf05722e248056a1957b0', '2022-01-19 23:31:06', '2022-03-29 07:23:56', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'json', '');
INSERT INTO `config_info` VALUES (29, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 192.168.111.10\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n\nfeign:\n  sentinel:\n    enabled: true\n', 'c39df769606aa20b2edbaf401f471101', '2022-01-23 20:49:27', '2022-03-29 05:36:57', 'nacos', '0:0:0:0:0:0:0:1', '', '791df34c-7c81-453e-b01d-375e4a30b834', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (31, 'gateway-dev.yaml', 'SECURITY_GROUP', 'server:\n  port: 8222\n  tomcat:\n    connection-timeout: 50000\n  \nspring:\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          enabled: true\n      routes[0]:\n        id: college-dormitory-security\n        uri: lb://college-dormitory-security\n        predicates: Path=/**', '9e8fb12b0bd05491ed954306087ff114', '2022-01-23 21:47:42', '2022-03-20 20:02:44', 'user_hxl', '182.100.21.93', '', '791df34c-7c81-453e-b01d-375e4a30b834', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (40, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', 'spring:\n#   application:\n#     name: equipment\n  redis:\n    host: 192.168.111.10\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#  cloud:\n#    nacos:\n#      discovery:\n#        server-addr: 1.116.117.152:8848\n#        group: EQUIPMENT_GROUP\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n###      config:\n###        server-addr: 1.116.117.152:8848\n###        file-extension: yaml\n###        group: SECURITY_GROUP_GROUP\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9010\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '74508984d2a5a0bf8782427226b95dd3', '2022-03-14 20:33:33', '2022-03-28 12:02:35', 'nacos', '0:0:0:0:0:0:0:1', '', '791df34c-7c81-453e-b01d-375e4a30b834', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (43, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', 'spring:\n  servlet:\n      multipart:\n        enabled: true #是否启用http上传处理\n        max-file-size: 10MB #上传文件 最大值限制\n        max-request-size: 10MB #请求 最大值限制\n  redis:\n    host: 192.168.111.10\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\nserver:\n  port: 9011\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n\n', 'ae8b4d6d0e5d6a48f3759a55cb8ae904', '2022-03-15 21:59:43', '2022-03-28 12:02:44', 'nacos', '0:0:0:0:0:0:0:1', '', '791df34c-7c81-453e-b01d-375e4a30b834', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (69, 'reportStatistics', 'REPORTSTATISTICS_GROUP', '[\n    {\n        \"resource\": \"inAndOut\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectRecord\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectAccessAfter11\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectNoAccess\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"getQrCode\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }\n]', 'ae05aacb8a13281fe73d9a0306671b57', '2022-03-29 07:33:18', '2022-03-29 07:39:08', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'json', '');
INSERT INTO `config_info` VALUES (72, 'equipment', 'EQUIPMENT_GROUP', '[\n    {\n        \"resource\": \"insert\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"update\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"delete\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"page\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"insertUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },{\n        \"resource\": \"updateUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"deleteUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectUser1\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }\n]', 'c1c8de361a2265c409872717050b281d', '2022-03-29 07:51:07', '2022-03-29 07:56:48', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'json', '');
INSERT INTO `config_info` VALUES (75, 'college-dormitory-security', 'COLLEGE-DORMITORY-SECURITY_GROUP', '[{\n        \"resource\": \"global\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 3000,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }]', 'be5ee9aac329cbb069e8b90cf38ae461', '2022-03-29 08:01:33', '2022-03-29 08:41:18', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'json', '');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint UNSIGNED NOT NULL,
  `nid` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 86 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (29, 41, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000', 'f6f5870c7417a7ed8b86c22b45b9faca', '2022-03-01 09:16:13', '2022-02-28 19:16:13', 'user_hxl', '36.170.10.186', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 42, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000', 'd6e5cfe73cd45ee5425b1aa350fc2460', '2022-03-03 12:05:58', '2022-03-02 22:05:59', 'user_hxl', '36.170.10.186', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 43, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"file:F/image\"', '938015b4cd1b97b0a7dd6a2186e3bc2a', '2022-03-03 12:07:09', '2022-03-02 22:07:10', 'user_hxl', '36.170.10.186', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (0, 44, 'equipment-dev', 'EQUIPMENT_GROUP', '', 'spring:\r\n#   application:\r\n#     name: equipment\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\n#  cloud:\r\n#    nacos:\r\n#      discovery:\r\n#        server-addr: 1.116.117.152:8848\r\n#        group: EQUIPMENT_GROUP\r\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\n###      config:\r\n###        server-addr: 1.116.117.152:8848\r\n###        file-extension: yaml\r\n###        group: SECURITY_GROUP_GROUP\r\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\nserver:\r\n  port: 9010\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '15e07b76b644b5c2383a26f3517507f4', '2022-03-15 09:32:23', '2022-03-14 20:32:23', NULL, '182.102.0.52', 'I', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (39, 45, 'equipment-dev', 'EQUIPMENT_GROUP', '', 'spring:\r\n#   application:\r\n#     name: equipment\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\n#  cloud:\r\n#    nacos:\r\n#      discovery:\r\n#        server-addr: 1.116.117.152:8848\r\n#        group: EQUIPMENT_GROUP\r\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\n###      config:\r\n###        server-addr: 1.116.117.152:8848\r\n###        file-extension: yaml\r\n###        group: SECURITY_GROUP_GROUP\r\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\nserver:\r\n  port: 9010\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '15e07b76b644b5c2383a26f3517507f4', '2022-03-15 09:32:59', '2022-03-14 20:33:00', NULL, '182.102.0.52', 'D', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (0, 46, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', '', 'spring:\r\n#   application:\r\n#     name: equipment\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\n#  cloud:\r\n#    nacos:\r\n#      discovery:\r\n#        server-addr: 1.116.117.152:8848\r\n#        group: EQUIPMENT_GROUP\r\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\n###      config:\r\n###        server-addr: 1.116.117.152:8848\r\n###        file-extension: yaml\r\n###        group: SECURITY_GROUP_GROUP\r\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\nserver:\r\n  port: 9010\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '15e07b76b644b5c2383a26f3517507f4', '2022-03-15 09:33:32', '2022-03-14 20:33:33', NULL, '182.102.0.52', 'I', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 47, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"', 'd402b8109ac5fa776400304f942de61a', '2022-03-15 09:42:35', '2022-03-14 20:42:36', 'user_hxl', '182.102.0.52', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 48, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n\nfeign:\n  sentinel:\n    enabled: true', 'fa5534cc3ce66bfdaca0077ed24bab1e', '2022-03-15 11:01:17', '2022-03-14 22:01:17', 'user_hxl', '182.102.0.52', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (0, 49, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', '', 'spring:\r\n  servlet:\r\n      multipart:\r\n        enabled: true #是否启用http上传处理\r\n        max-file-size: 10MB #上传文件 最大值限制\r\n        max-request-size: 10MB #请求 最大值限制\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\nserver:\r\n  port: 9011\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n', 'd6ddf59200b696f6d072649140f15975', '2022-03-16 10:59:43', '2022-03-15 21:59:43', NULL, '106.224.74.145', 'I', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (4, 50, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', '', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n    username: user_hxl\n    password: hxl.201803\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n  port: 8089\n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', '8e0be840a13dcfbf7898721a7513ea7b', '2022-03-21 08:56:56', '2022-03-20 19:56:56', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 51, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '8374fdcbdf700afc5f72d84ed48789b1', '2022-03-21 08:57:13', '2022-03-20 19:57:14', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (31, 52, 'gateway-dev.yaml', 'SECURITY_GROUP', '', 'server:\n  port: 8222\n  \nspring:\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          enabled: true\n      routes[0]:\n        id: college-dormitory-security\n        uri: lb://college-dormitory-security\n        predicates: Path=/**', '24f511dfa8918bf4b6b201f1eac80568', '2022-03-21 08:57:28', '2022-03-20 19:57:29', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (40, 53, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', '', 'spring:\r\n#   application:\r\n#     name: equipment\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\n#  cloud:\r\n#    nacos:\r\n#      discovery:\r\n#        server-addr: 1.116.117.152:8848\r\n#        group: EQUIPMENT_GROUP\r\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\n###      config:\r\n###        server-addr: 1.116.117.152:8848\r\n###        file-extension: yaml\r\n###        group: SECURITY_GROUP_GROUP\r\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\r\nserver:\r\n  port: 9010\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '15e07b76b644b5c2383a26f3517507f4', '2022-03-21 08:57:42', '2022-03-20 19:57:42', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (43, 54, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', '', 'spring:\r\n  servlet:\r\n      multipart:\r\n        enabled: true #是否启用http上传处理\r\n        max-file-size: 10MB #上传文件 最大值限制\r\n        max-request-size: 10MB #请求 最大值限制\r\n  redis:\r\n    host: 1.116.117.152\r\n    port: 6379\r\n    password: hxl.201803\r\n  datasource:\r\n      type: com.alibaba.druid.pool.DruidDataSource\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\r\n      username: user_hxl\r\n      password: hxl.201803\r\nserver:\r\n  port: 9011\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath*:xml/*.xml\r\n  configuration:\r\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n', 'd6ddf59200b696f6d072649140f15975', '2022-03-21 08:57:54', '2022-03-20 19:57:54', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (4, 55, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', '', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n    username: user_hxl\n    password: hxl.201803\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n    connection-timeout: 20000\n  port: 8089\n    \n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', 'f8a1f838946fe2d163a2d2b229535630', '2022-03-21 09:02:18', '2022-03-20 20:02:19', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 56, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 20000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '8605ea550f93dc4fb29418cae8d81148', '2022-03-21 09:02:32', '2022-03-20 20:02:32', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (31, 57, 'gateway-dev.yaml', 'SECURITY_GROUP', '', 'server:\n  port: 8222\n  tomcat:\n    connection-timeout: 20000\n  \nspring:\n  cloud:\n    gateway:\n      discovery:\n        locator:\n          enabled: true\n      routes[0]:\n        id: college-dormitory-security\n        uri: lb://college-dormitory-security\n        predicates: Path=/**', 'b268e0f568c8a96ddc0d7eddf8c4021d', '2022-03-21 09:02:43', '2022-03-20 20:02:44', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (40, 58, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', '', 'spring:\n#   application:\n#     name: equipment\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#  cloud:\n#    nacos:\n#      discovery:\n#        server-addr: 1.116.117.152:8848\n#        group: EQUIPMENT_GROUP\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n###      config:\n###        server-addr: 1.116.117.152:8848\n###        file-extension: yaml\n###        group: SECURITY_GROUP_GROUP\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9010\n  tomcat:\n    connection-timeout: 20000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '28fcdac10797789e2408de8582d6856a', '2022-03-21 09:02:55', '2022-03-20 20:02:56', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (43, 59, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', '', 'spring:\n  servlet:\n      multipart:\n        enabled: true #是否启用http上传处理\n        max-file-size: 10MB #上传文件 最大值限制\n        max-request-size: 10MB #请求 最大值限制\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\nserver:\n  port: 9011\n  tomcat:\n    connection-timeout: 20000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n\n', '70143a115276e1e624513433962020b4', '2022-03-21 09:03:06', '2022-03-20 20:03:07', 'user_hxl', '182.100.21.93', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (4, 60, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', '', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n    username: user_hxl\n    password: hxl.201803\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n    connection-timeout: 50000\n  port: 8089\n    \n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', 'f6d56c93fb7164dff685ef6d70279364', '2022-03-28 13:50:06', '2022-03-28 05:50:06', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 61, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '12bcc39f301eb190e30c6576aab66f5a', '2022-03-28 13:50:32', '2022-03-28 05:50:33', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 62, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '500b0b889a82c0d7d260dfb1d0be55b3', '2022-03-28 13:51:08', '2022-03-28 05:51:09', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 63, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', 'a1d97e8cf30e9743ee3542f278cc1339', '2022-03-28 13:51:36', '2022-03-28 05:51:36', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (4, 64, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', '', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n    username: user_hxl\n    password: hxl201803\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n    connection-timeout: 50000\n  port: 8089\n    \n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', 'bc8b95c34b756267331a219635d00ada', '2022-03-28 13:51:47', '2022-03-28 05:51:47', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (40, 65, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', '', 'spring:\n#   application:\n#     name: equipment\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\n#  cloud:\n#    nacos:\n#      discovery:\n#        server-addr: 1.116.117.152:8848\n#        group: EQUIPMENT_GROUP\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n###      config:\n###        server-addr: 1.116.117.152:8848\n###        file-extension: yaml\n###        group: SECURITY_GROUP_GROUP\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9010\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '7b91d5004270a32a2ca41744319f9363', '2022-03-28 13:52:11', '2022-03-28 05:52:12', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (43, 66, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', '', 'spring:\n  servlet:\n      multipart:\n        enabled: true #是否启用http上传处理\n        max-file-size: 10MB #上传文件 最大值限制\n        max-request-size: 10MB #请求 最大值限制\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://1.116.117.152:3306/collegedormitorysafetymanagementsystem?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8\n      username: user_hxl\n      password: hxl.201803\nserver:\n  port: 9011\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n\n', 'e7cfe2935d5ff2e15fb73871a36a5ad4', '2022-03-28 13:52:29', '2022-03-28 05:52:29', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (4, 67, 'face-recognition-dev.yaml', 'FACERECOGNITION_GROUP', '', 'spring:\n  servlet:\n    multipart:\n      enabled: true #是否启用http上传处理\n      max-file-size: 10MB #上传文件 最大值限制\n      max-request-size: 10MB #请求 最大值限制\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driver-class-name: com.mysql.cj.jdbc.Driver\n    url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n    username: user_hxl\n    password: hxl201803\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n\n\n\n\nserver:\n  max-http-header-size: 2MB   #请求头 最大值限制\n  #项目访问端口\n  tomcat:\n    max-http-form-post-size: 20MB\n    connection-timeout: 50000\n  port: 8089\n    \n\nface-recognition-config:\n  faceRecognitionConfig:\n      sdkPath: E:/arcsoft_lib\n      appId: GNuMURUPPoiJiaPZpSZd7V3Kz6gtF9Yf2tSzqtj2zt5o #sdk appId\n      sdkKey: hHrxM8qqp9ts3HhiwTTxmvFE1QamgJaGHUEmVEqQ1Lc #sdk sdkKey\n      detectPoolSize: 5  #人脸识别 引擎池大小\n      comparePoolSize: 6 #人脸比对 引擎池大小\n      compareThreadSize: 8 #人脸比对 线程池大小\n      passRate: 0.82\n      fileSize: 2097152\n      imageSavePath: G:\\\\image #图片保存路径\n\nmybatis-plus:\n  configuration:\n    map-underscore-to-camel-case: true  #开始mybatis驼峰命名映射\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\nlogging:\n  level:\n    root: info\n    com.lrm: debug\n  file: log/blog-dev.log\n  \n\n\n', '7f678564f89a33785c3b317ede55d13e', '2022-03-28 20:02:04', '2022-03-28 12:02:04', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 68, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '58321e4c167048308b0a101668dd1764', '2022-03-28 20:02:20', '2022-03-28 12:02:20', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (40, 69, 'equipment-dev.yaml', 'EQUIPMENT_GROUP', '', 'spring:\n#   application:\n#     name: equipment\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#  cloud:\n#    nacos:\n#      discovery:\n#        server-addr: 1.116.117.152:8848\n#        group: EQUIPMENT_GROUP\n#        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n###      config:\n###        server-addr: 1.116.117.152:8848\n###        file-extension: yaml\n###        group: SECURITY_GROUP_GROUP\n###        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9010\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl', '06b1c0e4f6afea7c31d905474eefe098', '2022-03-28 20:02:34', '2022-03-28 12:02:35', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (43, 70, 'reportStatistics-dev.yaml', 'REPORTSTATISTICS_GROUP', '', 'spring:\n  servlet:\n      multipart:\n        enabled: true #是否启用http上传处理\n        max-file-size: 10MB #上传文件 最大值限制\n        max-request-size: 10MB #请求 最大值限制\n  redis:\n    host: 1.116.117.152\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\nserver:\n  port: 9011\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath*:xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n\n', '909956cea70f118cd5478da73021e97b', '2022-03-28 20:02:44', '2022-03-28 12:02:44', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (29, 71, 'college-dormitory-security-dev.yaml', 'SECURITY_GROUP', '', 'spring:\n#   application:\n#     name: college-dormitory-security\n  redis:\n    host: 192.168.111.10\n    port: 6379\n    password: hxl.201803\n  datasource:\n      type: com.alibaba.druid.pool.DruidDataSource\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      url: jdbc:mysql://127.0.0.1:3306/collegedormitorysafetymanagementsystem?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC\n      username: user_hxl\n      password: hxl201803\n#   cloud:\n#     nacos:\n#       discovery:\n#         server-addr: 1.116.117.152:8848\n#         group: SECURITY_GROUP\n#         namespace: 791df34c-7c81-453e-b01d-375e4a30b834\n# #      config:\n# #        server-addr: 1.116.117.152:8848\n# #        file-extension: yaml\n# #        group: SECURITY_GROUP_GROUP\n# #        namespace: 791df34c-7c81-453e-b01d-375e4a30b834\nserver:\n  port: 9000\n  tomcat:\n    connection-timeout: 50000\n\nmybatis-plus:\n  mapper-locations: classpath:ncu/hxl/collegeDormitorySecurity/mapper/xml/*.xml\n  configuration:\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n\n# management:\n#   endpoints:\n#     web:\n#       exposure:\n#         include: \'*\'\n\n#logging:\n#  level:\n#    org:\n#      springframework:\n#        security: debug\nsecurity-config:\n  tokenSignKey: \"123456\"\n  tokenEcpiration: 86000000\n  staticAccessPath: \"/verifyCode\"\n  uploadFolder: \"F:/verifyCode\"\n', '2d33f90af6d3f2d13376fb6808387a7a', '2022-03-29 13:36:57', '2022-03-29 05:36:57', 'nacos', '0:0:0:0:0:0:0:1', 'U', '791df34c-7c81-453e-b01d-375e4a30b834');
INSERT INTO `his_config_info` VALUES (13, 72, 'face-recognition', 'FACERECOGNITION_GROUP', '', '[\n    {\n        \"resource\": \"test\",\n        \"grade\": 0,\n        \"count\": 300,\n        \"timeWindow\": 1,\n        \"minRequestAmount\": 6,        \n        \"statIntervalMs\": 3000,\n        \"slowRatioThreshold\": 0.2\n    },\n    {\n        \"resource\": \"testing\",\n        \"grade\": 0,\n        \"count\": 1000,\n        \"timeWindow\": 1,\n        \"minRequestAmount\": 6,        \n        \"statIntervalMs\": 3000,\n        \"slowRatioThreshold\": 0.2\n    },\n    {\n        \"resource\": \"register\",\n        \"grade\": 0,\n        \"count\": 800,\n        \"timeWindow\": 1,\n        \"minRequestAmount\": 6,        \n        \"statIntervalMs\": 3000,\n        \"slowRatioThreshold\": 0.2\n    }\n]', '60b7c50818eacffa6348a29bd5ac2622', '2022-03-29 15:01:25', '2022-03-29 07:01:25', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 73, 'face-recognition', 'FACERECOGNITION_GROUP', '', '[\n    {\n        \"resource\": \"select\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"register\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"delete\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"testing\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 2,\n        \"clusterMode\": false\n    }\n]', '09a9defb30ddf05722e248056a1957b0', '2022-03-29 15:11:53', '2022-03-29 07:11:54', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (13, 74, 'face-recognition', 'FACERECOGNITION_GROUP', '', '[\n    {\n        \"resource\": \"select\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 1,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"register\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"delete\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"testing\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 2,\n        \"clusterMode\": false\n    }\n]', '1987aa21f2392110273b032bab6716c0', '2022-03-29 15:23:56', '2022-03-29 07:23:56', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (19, 75, 'face-recognition-consumer', 'FACERECOGNITION_GROUP', '', '[\n   \n   {\n        \"resource\": \"register\",\n        \"limitApp\": \"default\",\n        \"grade\": \"1\",\n        \"count\": \"10\",\n        \"strategy\": \"0\",\n        \"controlBehavior\": \"0\",\n        \"clusterMode\": false\n    }\n    ,\n   {\n        \"resource\": \"testing\",\n        \"limitApp\": \"default\",\n        \"grade\": \"1\",\n        \"count\": \"10\",\n        \"strategy\": \"0\",\n        \"controlBehavior\": \"0\",\n        \"clusterMode\": false\n    }\n]', '8ce01c0b4cb065668379eacbe07ee726', '2022-03-29 15:31:54', '2022-03-29 07:31:55', NULL, '0:0:0:0:0:0:0:1', 'D', '');
INSERT INTO `his_config_info` VALUES (0, 76, 'reportStatistics', 'REPORTSTATISTICS_GROUP', '', '[\r\n    {\r\n        \"resource\": \"inAndOut\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectRecord\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectAccessAfter11\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectNoAccess\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"getQrCode\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }\r\n]', 'ad9609e3c826a4bb008f7c5a83e55bc6', '2022-03-29 15:33:18', '2022-03-29 07:33:18', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (69, 77, 'reportStatistics', 'REPORTSTATISTICS_GROUP', '', '[\r\n    {\r\n        \"resource\": \"inAndOut\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectRecord\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectAccessAfter11\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectNoAccess\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"getQrCode\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }\r\n]', 'ad9609e3c826a4bb008f7c5a83e55bc6', '2022-03-29 15:34:00', '2022-03-29 07:34:00', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (69, 78, 'reportStatistics', 'REPORTSTATISTICS_GROUP', '', '[\n    {\n        \"resource\": \"inAndOut\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectRecord\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 1,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectAccessAfter11\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectNoAccess\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"getQrCode\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }\n]', 'eda26028f370068c6105d325dc8fa289', '2022-03-29 15:39:07', '2022-03-29 07:39:08', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 79, 'equipment', 'EQUIPMENT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"insert\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"update\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"delete\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"page\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"insertUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },{\r\n        \"resource\": \"updateUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"deleteUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectUser1\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }\r\n]', '573f55cdd638281b54e10ea5a4fcb0ae', '2022-03-29 15:51:07', '2022-03-29 07:51:07', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (72, 80, 'equipment', 'EQUIPMENT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"insert\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"update\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"delete\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"page\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"insertUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },{\r\n        \"resource\": \"updateUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"deleteUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectUser\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    },\r\n    {\r\n        \"resource\": \"selectUser1\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }\r\n]', '573f55cdd638281b54e10ea5a4fcb0ae', '2022-03-29 15:52:11', '2022-03-29 07:52:11', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (72, 81, 'equipment', 'EQUIPMENT_GROUP', '', '[\n    {\n        \"resource\": \"insert\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"update\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"delete\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"page\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"insertUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },{\n        \"resource\": \"updateUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"deleteUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectUser\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 100,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    },\n    {\n        \"resource\": \"selectUser1\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 1,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }\n]', '3bb8cb07e244edd09ab65fc43f07923c', '2022-03-29 15:56:47', '2022-03-29 07:56:48', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 82, 'college-dormitory-security', 'COLLEGE-DORMITORY-SECURITY_GROUP', '', '[{\r\n        \"resource\": \"global\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }]', '431a52c45a0e4acfbdcb11ae943c1e00', '2022-03-29 16:01:33', '2022-03-29 08:01:33', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (75, 83, 'college-dormitory-security', 'COLLEGE-DORMITORY-SECURITY_GROUP', '', '[{\r\n        \"resource\": \"global\",\r\n        \"limitApp\": \"default\",\r\n        \"grade\": 1,\r\n        \"count\": 100,\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0,\r\n        \"clusterMode\": false\r\n    }]', '431a52c45a0e4acfbdcb11ae943c1e00', '2022-03-29 16:40:33', '2022-03-29 08:40:34', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (75, 84, 'college-dormitory-security', 'COLLEGE-DORMITORY-SECURITY_GROUP', '', '[{\n        \"resource\": \"global\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 1,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }]', '47e4d57ed8e43b3e6e7b786cbc5e132b', '2022-03-29 16:41:12', '2022-03-29 08:41:12', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (75, 85, 'college-dormitory-security', 'COLLEGE-DORMITORY-SECURITY_GROUP', '', '[{\n        \"resource\": \"global\",\n        \"limitApp\": \"default\",\n        \"grade\": 1,\n        \"count\": 1000,\n        \"strategy\": 0,\n        \"controlBehavior\": 0,\n        \"clusterMode\": false\n    }]', '20c107ee664ff9025c70638a36a1d19b', '2022-03-29 16:41:17', '2022-03-29 08:41:18', 'nacos', '0:0:0:0:0:0:0:1', 'U', '');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `resource` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (1, '1', '791df34c-7c81-453e-b01d-375e4a30b834', 'dev', '开发环境', 'nacos', 1642609817154, 1642609817154);
INSERT INTO `tenant_info` VALUES (2, '1', '4cfbd3b5-3e16-4a58-b43e-59222f1d5816', 'pro', '运行环境', 'nacos', 1642609850529, 1642609850529);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('user_hxl', '$2a$10$csF5Tn.Yc67s/f.3pRgM9eE/60rDTyTEO4Lm0h1Z2/OjNmYpRoY2y', 1);

SET FOREIGN_KEY_CHECKS = 1;
